apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bet-commands
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bet-settle
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bet-settle-job
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: customer-commands
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: customer-events
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: market-commands
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3